"""Golden outputs were captured from pre-extraction equations, not generated by new code."""
import json
from pathlib import Path
from types import SimpleNamespace
import torch
from wheel_legged_gym.domain.rewards.api import evaluate
from wheel_legged_gym.domain.rewards.inputs import RewardInputs


def decode(value):
    if isinstance(value,dict):
        if set(value)=={'dtype','values'}:
            return torch.tensor(value['values'],dtype=getattr(torch,value['dtype']))
        return {k:decode(v) for k,v in value.items()}
    return value


def config(value):
    return SimpleNamespace(**{k:config(v) for k,v in value.items()}) if isinstance(value,dict) else value


def test_all_reward_branches_match_original_outputs_without_simulator():
    fixture=json.loads((Path(__file__).parent/'fixtures/reward_equivalence.json').read_text())
    count=0
    for case in fixture['cases']:
        state=decode(case['state']);state['cfg']=config(case['config']);inputs=RewardInputs(**state)
        original_tensors={k:v.clone() for k,v in state.items() if torch.is_tensor(v)}
        for name,expected in case['expected'].items():
            result=evaluate(name,inputs);expected=decode(expected)
            if isinstance(expected,dict):
                assert result.keys()==expected.keys()
                for key in expected:assert torch.equal(result[key],expected[key]),(name,key)
            else:assert torch.equal(result,expected),name
            count+=1
        for key,before in original_tensors.items():assert torch.equal(before,state[key]),key
    assert count==216
